name: Bug report
description: Report a bug in evergit
title: '[BUG] '
labels: ['bug']

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!

    - type: input
      id: evergit_version
      attributes:
          label: evergit version
          description: Please provide the version of evergit you are using.
          placeholder: 'e.g. 1.0.0'

    - type: input
      id: node_version
      attributes:
          label: Node version
          description: Please provide the version of Node.js you are using.
          placeholder: 'e.g. 14.17.0'

    - type: textarea
      id: description
      attributes:
          label: Bug description
          description: Please provide a clear and concise description of the bug.
          placeholder: 'Describe the bug'

    - type: textarea
      id: steps_to_reproduce
      attributes:
          label: Steps to reproduce
          description: Please provide the steps to reproduce the bug.
          placeholder: 'Steps to reproduce'

    - type: textarea
      id: expected_behavior
      attributes:
          label: Expected behavior
          description: Please describe what you expected to happen.
          placeholder: 'Describe the expected behavior'

    - type: textarea
      id: additional_context
      attributes:
          label: Additional context
          description: Add any other context about the problem here. For example, screenshots, logs, etc.
          placeholder: 'Add any other context about the problem here'
